const dataCircuitBreaker = {
    id: '',
    location_id: '',
    properties: JSON.parse('{"asset":"Circuit breaker","asset_type":"","serial_no":"","manufacturer":"","manufacturer_type":"","manufacturing_year":"","asset_system_code":"","apparatus_id":"","feeder":""}'),
    circuitBreaker: JSON.parse('{"numberOfPhase": "","numberOfInterruptPhase": "","poleOperation":"","PreInsert":true,"PIR":"","gradingCap":true,"capacitorValue":"","interruptMedium":"","tankType":""}'),
    ratings: JSON.parse('{"rated_frequency":"Custom","rated_frequency_custom":"","rated_voltage_ll":"","rated_current":"","rated_shortcircuit":"","shortcircuit_nominal":"","rated_insulation":"","rated_interrupt":"","interrupt_duty":"","rated_power_closing":"","rated_power_open":"","rated_power_charge":""}'),
    contactSys: JSON.parse('{"nominalTravel":"","dampTime":"","nozzleLen":""}'),
    others: JSON.parse('{"totalWithgas":"","weightGas":"","VolumeGas":"","pa":"","Celsius":""}'),
    operating: JSON.parse('{"table":[[],[],{"component":"Auxiliary circuits","ratedVoltage":"","ratedCurrent":"","frequency":"","acdc":"DC"},{"component":"Motor","ratedVoltage":"","ratedCurrent":"","frequency":"","acdc":"AC"}],"asset_type":"hydraulic","serial":"","manufacturer":"","manufacturer_year":"","manufacturer_type":"","asset_system_code":"","numberTripCoil":"","numberCloseCoil":"","pa":"","Celsius":""}'),
    assessmentLimits: JSON.parse('{"limits":"Relative","contactSys":{"abs":{"rmin":"","rmax":""},"rel":{"rref":"","rdev":""}},"openTime":{"abs":[{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""}],"rel":[{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""},{"rref":"","tdevZ":"","tdevN":""}]},"contactTravel":{"abs":[{"dmin":"","dmax":""},{"dmin":"","dmax":""},{"dmin":"","dmax":""},{"dmin":"","dmax":""},{"dmin":"","dmax":""},{"dmin":"","dmax":""},{"dmin":"","dmax":""},{"dmin":"","dmax":""}],"rel":[{"dref":"","ddev":""},{"dref":"","ddev":""},' + 
    '{"dref":"","ddev":""},{"dref":"","ddev":""},{"dref":"","ddev":""},{"dref":"","ddev":""},{"dref":"","ddev":""},{"dref":"","ddev":""}]},"auxContact":{"abs":{"trip":[{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""}],"close":[{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""},{"tmin":"","tmax":""}]},"rel":{"trip":[{"tref":"","tdef":""},{"tref":"","tdef":""},{"tref":"","tdef":""},{"tref":"","tdef":""},{"tref":"","tdef":""},{"tref":"","tdef":""}],"close":[{"tref":"","tdev":""},{"tref":"","tdev":""},{"tref":"","tdev":""},{"tref":"","tdev":""},{"tref":"","tdev":""},{"tref":"","tdev":""}]}},"miscell":{"abs":[{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""}],"rel":[{"ref":"","dev":""},{"ref":"","dev":""},{"ref":"","dev":""},'+
    '{"ref":"","dev":""}]},"coilCharacter":{"abs":[{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""}],"rel":[{"ref":"","devZ":"","devN":""},{"ref":"","devZ":"","devN":""},{"ref":"","devZ":"","devN":""},{"ref":"","devZ":"","devN":""},{"ref":"","devZ":"","devN":""},{"ref":"11","devZ":"","devN":""},{"ref":"","devZ":"","devN":""},{"ref":"","devZ":"","devN":""}]},"pickupVol":{"abs":[{"vmin":"","vmax":""},{"vmin":"","vmax":""}],"rel":[{"vref":"","vdev":""},{"vref":"","vdev":""}]},"motorChar":{"abs":[{"min":"","max":""},{"min":"","max":""},{"min":"","max":""},{"min":"","max":""}],"rel":[{"ref":"","dev":""},{"ref":"","dev":""},{"ref":"","dev":""},{"ref":"","dev":""}]},"underVoltageR":{"abs":{"min":"","max":""},"rel":{"ref":"","dev":""}},"overcurrentR":{"abs":{"min":"","max":""},"rel":{"ref":"","dev":""}}}'),
    extend: null
}

export default dataCircuitBreaker