export const PhaseCode = {
    A: 'A',
    AB: 'AB',
    ABC: 'ABC',
    ABCN: 'ABCN',
    ABN: 'ABN',
    AC: 'AC',
    ACN: 'ACN',
    AN: 'AN',
    B: 'B',
    BC: 'BC',
    BCN: 'BCN',
    BN: 'BN',
    C: 'C',
    CN: 'CN',
    N: 'N',
    none : 'none',
    s1: 's1',
    s12: 's12',
    s12N: 's12N',
    s1N: 's1N',
    s2: 's2',
    s2N: 's2N',
    X: 'X',
    XN: 'XN',
    XY: 'XY',
    XYN: 'XYN'
}