/* eslint-disable */
// Auto-generated from 'Quan ly thiet bi OMICRON, HVI - HCM ETC.xlsx'
// 73 testing equipment records (OMICRON + HVI). Replace with API data later.
export default [
  {
    "id": 1,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "GD902M",
    "software": "Basic + Distance + Differential + GOOSE + Overcurrent + Advanced Distance + Advanced Differential + Advanced TransPlay + Autoreclosure",
    "made": "2014-06-03",
    "inservice": "2014",
    "repair": "- Bị hỏng lần 1 vào 02-2015 (HNT256 board), bảo hành tại Áo 03-2015.\n- Bị hỏng lần 2 vào 05-2017, đang đem đi sửa tại Áo.\n- ngày 12/9/2018 : Không giao tiếp được mặc dù cổng USB, ETH báo ready. \"9/12/2018 2:16:35 PM: (ENG074) Could not activate power supply\". Kết luận : lỗi phần cứng, cần được sửa.\nĐưa sang Áo sửa chữa thay bo mạch OWF, LLP256, MIC256"
  },
  {
    "id": 2,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "GD904M",
    "software": "Basic + Distance + Differential + GOOSE",
    "made": "2014-06-03",
    "inservice": "2014",
    "repair": "- Bị hỏng lần 1 vào 05-2015 (HNT256 board, OWF, LV256p), bảo hành tại HK 06-2015.\n- Bị hỏng lần 2 tháng 11/2016. Sửa tại Áo (HV256 board). Có con ốc bên ngoài rơi vào làm ngắn mạch HV board."
  },
  {
    "id": 3,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "LC321U",
    "software": "Basic +Overcurrent + Advanced Distance + Advanced Differential + Advanced TransPlay + Autoreclosure + GOOSE",
    "made": "2017-05-30",
    "inservice": "2017",
    "repair": "- Lỗi  communication board MIC/LL (12/1/2024), chuyển về Hãng sửa chữa"
  },
  {
    "id": 4,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "LC323U",
    "software": "Basic +Overcurrent + Advanced Distance + Advanced Differential + Advanced TransPlay + Autoreclosure + GOOSE",
    "made": "2017-05-30",
    "inservice": "2017",
    "repair": "- Lỗi kênh dòng đầu ra (A), chuyển về hãng sửa chữa (07/10/2025)"
  },
  {
    "id": 5,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "PF529Y",
    "software": "Essential + Overcurrent + Distance + Advanced Distance + Diff. + Advanced Differential + Advanced TransPlay + SV + GOOSE + RST + ELT1",
    "made": "2020-11-15",
    "inservice": "2020-12-01",
    "repair": ""
  },
  {
    "id": 6,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "PF530Y",
    "software": "Essential + Overcurrent + Distance + Advanced Distance + Diff. + Advanced Differential + Advanced TransPlay + SV + GOOSE + RST + ELT1",
    "made": "2020-11-15",
    "inservice": "2020-12-01",
    "repair": "- Lỗi ENG074, gửi về Hãng sửa chữa (11/7/2022)"
  },
  {
    "id": 7,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ đồng bộ thời gian",
    "model": "CMGPS 588",
    "serial": "JF184V",
    "software": "",
    "made": "2020-11-15",
    "inservice": "2020-12-01",
    "repair": ""
  },
  {
    "id": 8,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ đồng bộ thời gian",
    "model": "CMGPS 588",
    "serial": "JF185V",
    "software": "",
    "made": "2020-11-15",
    "inservice": "2020-12-01",
    "repair": ""
  },
  {
    "id": 9,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Phần mềm phân tích IED",
    "model": "IEDScout",
    "serial": "",
    "software": "",
    "made": "2014-06-03",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 10,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "QB405W",
    "software": "- CP Quick Test card\n- CP CT Test card\n- CP VT Test card\n- CP Transformer Test card\n- CP Sequencer Test card\n- CP Ramping Test card\n- PTM software",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": "- Bị hỏng đầu 2kV đem đi sửa 06/2016 tại Áo. Thay thế S2KVCPT, M2KVCPT. Tháng 07/2016 trả về.\n'- Hỏng kênh dòng 6ADC, xuất hiện thông báo quá tải, gửi về Hãng sửa chữa (18/1/2022)"
  },
  {
    "id": 11,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng tạo dòng 2000A",
    "model": "CP CB2",
    "serial": "NM581P",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 12,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo tang denta và điện dung",
    "model": "CP TD1",
    "serial": "MC793U",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 13,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo 3 pha máy biến áp",
    "model": "CP SB1",
    "serial": "GC606W",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 14,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo tổng trở đường dây",
    "model": "CP CU1 + CP GB1",
    "serial": "KC548J",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 15,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Cốc thử Tang Delta của dầu",
    "model": "CP TC12",
    "serial": "-",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 16,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hộp xả nhanh điện tích cho máy biến áp",
    "model": "CP DB1",
    "serial": "CB047D",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 17,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Đồng hồ đo điện áp bước và điện áp tiếp xúc",
    "model": "CP AL1",
    "serial": "-",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 18,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ kháng bù",
    "model": "CP CR500",
    "serial": "KE230X",
    "software": "",
    "made": "2014-08-04",
    "inservice": "2014",
    "repair": ""
  },
  {
    "id": 19,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích đáp ứng tần số",
    "model": "FRANEO 800",
    "serial": "BC047R",
    "software": "",
    "made": "2015-11-04",
    "inservice": "2015",
    "repair": ""
  },
  {
    "id": 20,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo và phân tích phóng điện cục bộ",
    "model": "MPD 600",
    "serial": "JJ805E, JJ806E;\nJJ808E;\nJJ809E",
    "software": "Advance + 3FREQ",
    "made": "2016-06-30",
    "inservice": "2016",
    "repair": "- JJ805E, JJ806E hiệu chuẩn lại tại Nhà sản xuất (19/3/2026)\n'- JJ808E, JJ809E đầu V input nghị ngắn mạch với vỏ, chuyển về hãng sửa chữa (19/12/2025)"
  },
  {
    "id": 21,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo tang denta và điện dung",
    "model": "TANDO 700",
    "serial": "BJ250F, BJ251F",
    "software": "Advanced package",
    "made": "2016-06-30",
    "inservice": "2016",
    "repair": ""
  },
  {
    "id": 22,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo và phân tích phóng điện cục bộ",
    "model": "MPD 800",
    "serial": "EC273R",
    "software": "MPD Suite software - Multi Application Pack.",
    "made": "2020-11-15",
    "inservice": "2020-12-02",
    "repair": ""
  },
  {
    "id": 23,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy cắt",
    "model": "CIBANO 500",
    "serial": "EC509G",
    "software": "Advanced Package + Motion Universal",
    "made": "2017-05-30",
    "inservice": "2017",
    "repair": "- Không kết nối được với máy tính điều khiển, gửi về hãng sửa chữa (24/12/2025)"
  },
  {
    "id": 24,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "SE889Y",
    "software": "- CP Quick Test card\n- CP CT Test card\n- CP VT Test card\n- CP TR Test card\n- CP Sequencer Test card\n- Demag Test card\n- PTM software",
    "made": "2017-05-30",
    "inservice": "2018",
    "repair": "- Hiệu chuẩn lại thiết bị tại Nhà sản xuất (06/4/2022)"
  },
  {
    "id": 25,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "SE890Y",
    "software": "- CP Quick Test card\n- CP CT Test card\n- CP VT Test card\n- CP TR Test card\n- CP Sequencer Test card\n- Demag Test card\n- PTM software",
    "made": "2017-05-30",
    "inservice": "2019",
    "repair": "- Hiệu chuẩn lại thiết bị tại Nhà sản xuất (06/4/2022)"
  },
  {
    "id": 26,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng tạo dòng 2000A",
    "model": "CP CB2",
    "serial": "QJ897P",
    "software": "",
    "made": "2017-05-30",
    "inservice": "2020",
    "repair": ""
  },
  {
    "id": 27,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo tang denta và điện dung",
    "model": "CP TD1",
    "serial": "QA700W",
    "software": "",
    "made": "2017-05-30",
    "inservice": "2021",
    "repair": ""
  },
  {
    "id": 28,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo 3 pha máy biến áp",
    "model": "CP SB1",
    "serial": "KA082W",
    "software": "",
    "made": "2017-05-30",
    "inservice": "2022",
    "repair": ""
  },
  {
    "id": 29,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy biến dòng",
    "model": "CT Analyzer",
    "serial": "NG882M",
    "software": "Advanced Package",
    "made": "2017-05-30",
    "inservice": "2023",
    "repair": ""
  },
  {
    "id": 30,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo 3 pha cho CT",
    "model": "CT SB2",
    "serial": "GK952V",
    "software": "",
    "made": "2017-05-30",
    "inservice": "2024",
    "repair": ""
  },
  {
    "id": 31,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "UG733C",
    "software": "- CP Quick Test card\n- CP CT Test card\n- CP Transformer Test card\n- Line impedance Test card",
    "made": "2019-04-10",
    "inservice": "2019-04-19",
    "repair": ""
  },
  {
    "id": 32,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo tang denta và điện dung",
    "model": "CP TD1",
    "serial": "RM282Z",
    "software": "",
    "made": "2019-04-10",
    "inservice": "2019-04-19",
    "repair": ""
  },
  {
    "id": 33,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo tổng trở đường dây",
    "model": "CP CU1 + CP GB1",
    "serial": "PC913M",
    "software": "",
    "made": "2019-04-10",
    "inservice": "2019-04-19",
    "repair": ""
  },
  {
    "id": 34,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "UG692C",
    "software": "- CP Quick Test card\n- CP CT Test card\n- Sequencer Test card",
    "made": "2019-03-10",
    "inservice": "2019-04-08",
    "repair": "- Lỗi phần cứng, màn hình không hiển thị khi được cấp nguồn, chuyển về hãng để sửa chữa (12/6/2024)"
  },
  {
    "id": 35,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm đa năng chuyên dụng cho lưới điện trung thế",
    "model": "COMPANO 100",
    "serial": "BM409G",
    "software": "Advanced + VOUT",
    "made": "2019-03-10",
    "inservice": "2019-04-08",
    "repair": ""
  },
  {
    "id": 36,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm recloser",
    "model": "ARCO 400",
    "serial": "CF478D",
    "software": "Standard Package",
    "made": "2019-07-10",
    "inservice": "2019-08-15",
    "repair": "- Mất kết nối và không ổn định tỏng quá trình thí nghiệm, chuyển về hãng đẻ sửa chữa (22/01/2025)"
  },
  {
    "id": 37,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm recloser",
    "model": "ARCO 400",
    "serial": "CF479D",
    "software": "Standard Package",
    "made": "2019-07-10",
    "inservice": "2019-08-15",
    "repair": ""
  },
  {
    "id": 38,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm máy biến áp",
    "model": "TESTRANO 600",
    "serial": "FG542Z",
    "software": "Universal + Touch Control",
    "made": "2020-10-20",
    "inservice": "2020-10-27",
    "repair": ""
  },
  {
    "id": 39,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm phân tích truyền tin cho TBA KTS",
    "model": "DANEO 400",
    "serial": "102250924",
    "software": "Standard package",
    "made": "2022-10-10",
    "inservice": "2022-10-26",
    "repair": ""
  },
  {
    "id": 40,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm phân tích truyền tin cho TBA KTS",
    "model": "DANEO 400",
    "serial": "102250919",
    "software": "Standard package",
    "made": "2022-10-10",
    "inservice": "2022-10-26",
    "repair": ""
  },
  {
    "id": 41,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Thiết bị phân tích máy cắt",
    "model": "CIBANO 500",
    "serial": "KF134K",
    "software": "Advanced Package",
    "made": "2021-09-08",
    "inservice": "2021-11-18",
    "repair": ""
  },
  {
    "id": 42,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm máy biến áp",
    "model": "TESTRANO 600",
    "serial": "102320378",
    "software": "Enhanced Package (No-Display)",
    "made": "2023-04-18",
    "inservice": "2023-12-12",
    "repair": ""
  },
  {
    "id": 43,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo rung động âm thanh OLTC",
    "model": "VAM1",
    "serial": "102350121",
    "software": "",
    "made": "2023-04-18",
    "inservice": "2023-12-12",
    "repair": ""
  },
  {
    "id": 44,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Thiết bị phân tích máy cắt",
    "model": "CIBANO 500",
    "serial": "102477391",
    "software": "",
    "made": "2024-07-26",
    "inservice": "2024-09-20",
    "repair": ""
  },
  {
    "id": 45,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy biến dòng",
    "model": "CT Analyzer",
    "serial": "102469608",
    "software": "Standard package",
    "made": "2024-07-26",
    "inservice": "2024-09-20",
    "repair": ""
  },
  {
    "id": 46,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy biến dòng",
    "model": "CT Analyzer",
    "serial": "102472007",
    "software": "Standard package",
    "made": "2024-07-26",
    "inservice": "2024-09-20",
    "repair": ""
  },
  {
    "id": 47,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm đa năng chuyên dụng cho lưới điện trung thế",
    "model": "COMPANO 100",
    "serial": "NN166C / 102576350",
    "software": "Advanced Package",
    "made": "2025-04-14",
    "inservice": "2025-06-27",
    "repair": ""
  },
  {
    "id": 48,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm rơle 3 pha",
    "model": "CMC 356",
    "serial": "NN551A / 102569965",
    "software": "Essential (ELTLLO1) + Adv. Differential + GOOSE + Sampled Values + CMGPS588 + RelaySimTest (inc NetSim Trans Ground Fault) + Overcurrent + Adv. Distance + Adv. TransPlay",
    "made": "2025-04-14",
    "inservice": "2025-06-27",
    "repair": ""
  },
  {
    "id": 49,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ đồng bộ thời gian",
    "model": "CMGPS 588",
    "serial": "102580583",
    "software": "",
    "made": "2025-04-14",
    "inservice": "2025-06-27",
    "repair": ""
  },
  {
    "id": 50,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm máy biến áp",
    "model": "TESTRANO 600",
    "serial": "NN539K / 102587285",
    "software": "Enhanced Package",
    "made": "2025-04-14",
    "inservice": "2025-06-27",
    "repair": ""
  },
  {
    "id": 51,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy cắt",
    "model": "CIBANO 500",
    "serial": "RN703F/ 102763719",
    "software": "Advanced Package",
    "made": "2026-03-10",
    "inservice": "2026-04-17",
    "repair": ""
  },
  {
    "id": 52,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy cắt",
    "model": "CIBANO 500",
    "serial": "RN618C/ 102752763",
    "software": "Advanced Package",
    "made": "2026-03-10",
    "inservice": "2026-04-17",
    "repair": ""
  },
  {
    "id": 53,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm recloser",
    "model": "ARCO 400",
    "serial": "RN752G/ 102781164",
    "software": "Standard Package (150V)",
    "made": "2026-03-10",
    "inservice": "2026-04-17",
    "repair": ""
  },
  {
    "id": 54,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm recloser",
    "model": "ARCO 400",
    "serial": "RN750G/ 102781162",
    "software": "Standard Package (150V)",
    "made": "2026-03-10",
    "inservice": "2026-04-17",
    "repair": ""
  },
  {
    "id": 55,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo 3 pha máy biến áp",
    "model": "CP SB1",
    "serial": "102697195",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 56,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo 3 pha máy biến áp",
    "model": "CP SB1",
    "serial": "102697194",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 57,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy biến dòng",
    "model": "CT Analyzer",
    "serial": "102810584",
    "software": "Advanced Package",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 58,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ phân tích máy biến dòng",
    "model": "CT Analyzer",
    "serial": "102810585",
    "software": "Advanced Package",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 59,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm máy biến áp",
    "model": "TESTRANO 600",
    "serial": "102810525",
    "software": "Enhanced Package",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 60,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm máy biến áp",
    "model": "TESTRANO 600",
    "serial": "102798084",
    "software": "Enhanced Package",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 61,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "102795846",
    "software": "Standard package",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 62,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm nhất thứ đa năng",
    "model": "CPC 100",
    "serial": "102795844",
    "software": "Standard package",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 63,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo tang denta và điện dung",
    "model": "CP TD15",
    "serial": "102756091",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 64,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Hợp bộ đo tang denta và điện dung",
    "model": "CP TD15",
    "serial": "102756090",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 65,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ kháng bù",
    "model": "CP CR600",
    "serial": "102700537",
    "software": "25H",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 66,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ kháng bù",
    "model": "CP CR600",
    "serial": "102712035",
    "software": "50H",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 67,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng tạo dòng 2000A",
    "model": "CP CB2",
    "serial": "102545909",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 68,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng tạo dòng 2000A",
    "model": "CP CB2",
    "serial": "102545908",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 69,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo tổng trở đường dây",
    "model": "CP CU1 + CP GB1",
    "serial": "102633370/ 102796915",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 70,
    "manufacturer": "OMICRON",
    "customer": "Công ty thí nghiệm điện lực TP Hồ Chí Minh",
    "name": "Bộ mở rộng đo tổng trở đường dây",
    "model": "CP CU1 + CP GB1",
    "serial": "102633371/ 102796916",
    "software": "",
    "made": "2026-05-21",
    "inservice": "",
    "repair": ""
  },
  {
    "id": 71,
    "manufacturer": "HVI",
    "customer": "Công ty Thí nghiệm Điện lực TP. Hồ Chí Minh",
    "enduser": "Công ty Thí nghiệm Điện lực TP. Hồ Chí Minh",
    "name": "Hợp bộ thí nghiệm cáp trung thế tần số thấp",
    "model": "VLF 65E",
    "serial": "1089, 1090, 1091",
    "software": "",
    "made": "2016",
    "inservice": "",
    "repair": "1089:\n- Sửa lần 1 (01/2018): Thay module PCF và Fuse board\n'1090:\n- Sửa lần 1 (07/2017): Thay module PCF\n- Sửa lần 2 (07/2018): bật nguồn + lên điện áp (khoảng 12 kV -> có tiếng nổ bụp + mất nguồn. Gửi sang hãng HVI để sửa chữa\n- Sửa lần 3 (02/2019): có hiện tượng đồ thị không còn hình Sin\n'1091:\n- Sửa lần 1 (07/2017): Thay module PCF\n- Sửa lần 2 (01/2018): Thay module PCF và Fuse board\n- Sửa lần 3 (05/2018): bật nguồn + lên điện áp (khoảng 12 kV -> có tiếng nổ bụp + mất nguồn. Gửi sang hãng HVI để sửa chữa",
    "version": ""
  },
  {
    "id": 72,
    "manufacturer": "HVI",
    "customer": "Công ty Thí nghiệm Điện lực TP. Hồ Chí Minh",
    "enduser": "Công ty Thí nghiệm Điện lực TP. Hồ Chí Minh",
    "name": "Thiết bị thí nghiệm cao áp",
    "model": "PFT-503CMF",
    "serial": "2345",
    "software": "",
    "made": "2019",
    "inservice": "",
    "repair": "",
    "version": ""
  },
  {
    "id": 73,
    "manufacturer": "HVI",
    "customer": "Công ty Thí nghiệm Điện lực TP. Hồ Chí Minh",
    "enduser": "Công ty Thí nghiệm Điện lực TP. Hồ Chí Minh",
    "name": "Thiết bị thí nghiệm cao áp",
    "model": "PFT-503CMF",
    "serial": "3425",
    "software": "",
    "made": "2025",
    "inservice": "",
    "repair": "",
    "version": ""
  }
]
