/* eslint-disable */
// Danh sách license/option mặc định tổng hợp từ file Excel
// (cột 'Gói phần mềm'). Dùng cho bảng chọn khi Add license.
export default [
    "25H",
    "3FREQ",
    "50H",
    "Adv. Differential",
    "Adv. Distance",
    "Adv. TransPlay",
    "Advance",
    "Advanced",
    "Advanced Differential",
    "Advanced Distance",
    "Advanced package",
    "Advanced TransPlay",
    "Autoreclosure",
    "Basic",
    "CMGPS588",
    "CP CT Test card",
    "CP Quick Test card",
    "CP Ramping Test card",
    "CP Sequencer Test card",
    "CP TR Test card",
    "CP Transformer Test card",
    "CP VT Test card",
    "Demag Test card",
    "Diff.",
    "Differential",
    "Distance",
    "ELT1",
    "Enhanced Package",
    "Enhanced Package (No-Display)",
    "Essential",
    "Essential (ELTLLO1)",
    "GOOSE",
    "Line impedance Test card",
    "Motion Universal",
    "MPD Suite software - Multi Application Pack.",
    "Overcurrent",
    "PTM software",
    "RelaySimTest (inc NetSim Trans Ground Fault)",
    "RST",
    "Sampled Values",
    "Sequencer Test card",
    "Standard Package",
    "Standard Package (150V)",
    "SV",
    "Touch Control",
    "Universal",
    "VOUT"
]
