const MANUFACTURER_MAP = {
  TransformerDataDto: [
    'ABB',
    'ABB Sécheron',
    'ACEC',
    'Aditya Vidyut Appliances Ltd.',
    'AEG',
    'Alstohm Savoisienne',
    'Alstom',
    'ANSALDO',
    'APEX',
    'Areva',
    'Areva Unido',
    'Artrans - Los Conce',
    'ASA Trafobau GmbH',
    'ASEA',
    'BBC',
    'Bharat Bijilee Ltd.',
    'Bharat Heavy Electricals, Ltd.',
    'BHEL',
    'Crompton Greaves',
    'DAIHEN',
    'DELTA STAR',
    'DIAMOND POWER INFRASTRUCTURE LIMITED',
    'EBG',
    'EFACEC',
    'EEMC',
    'electroputere',
    'Elettromeccania colombo',
    'ELIN',
    'ELTA',
    'Emco Transformers Ltd.',
    'Ferranti-Packard',
    'Fuji Electric',
    'FORTUNE ELECTRIC CO.,LTD.',
    'FIRST PHILEC',
    'FPE',
    'Franco Transfo',
    'GE PROLEC',
    'General Electric',
    'Getra',
    'HAMMOND',
    'HAVEC',
    'HAWKER SIDDELEY',
    'HEM',
    'Helmke',
    'HICO',
    'Hitachi Energy',
    'HOWARD',
    'HYOSUNG',
    'Hyundai',
    'IEM',
    'Imefy',
    'Italtrafo',
    'JAEPS',
    'Jeumont-Schneider',
    'JORDAN',
    'JSHP',
    'JSP',
    'JST',
    'KONČAR',
    'Kuhlman',
    'Leeper',
    'Matelec',
    'McGraw Edison',
    'MF Trasformatori',
    'MITSUBISHI',
    'NGEF',
    'OASA',
    'Ocrev',
    'Oerlikon',
    'OFFICINE TRANSFORMATORI ELECTRICI',
    'Parsons Peebles',
    'PAUWELS',
    'Peebles',
    'PENNSYLVANIA TRANSFORMER',
    'SAVOISIENNE',
    'Schneider Electric',
    'Schorch',
    'SGB',
    'Siemens',
    'SMIT',
    'TAMINI',
    'TBEA',
    'TELK',
    'TIRONI',
    'TOSHIBA',
    'TRAFO UNION',
    'UNIDO',
    'VEE',
    'Waukesha',
    'Westinghouse',
    'Wilson transformer',
    'ZTR'
    ],

  BushingAssetDto: [
    'ABB',
    'Electro composites',
    'HSP',
    'Micafil',
    'PCORE Electric',
    ],

  CircuitBreakerDto: [
    'ABB',
    'AEG',
    'Alstom',
    'Areva',
    'BBC',
    'Delle-Alstom',
    'General Electric',
    'HICO',
    'HVB',
    'Johnson & Phillips',
    'MITSUBISHI',
    'OFFICINE TRANSFORMATORI ELECTRICI',
    'PENNSYLVANIA BREAKER',
    'Sampletronics',
    'Siemens',
    'Sprecher & Schuh',
    'Westinghouse',
    ],

  CurrentTransformerDto: [
    'ABB',
    'ALCE',
    'Alstom',
    'Areva',
    'Kaisen',
    'Pfiffner',
    'Ritz',
    'Schneider Electric',
    'Siemens',
    'General Electric',
    'Mitsubishi Electric',
    'Toshiba',
    'Westinghouse',
    'Zelisko'
    ],

  VoltageTransformerDto: [
    'ABB',
    'ALCE',
    'Alstom',
    'Areva',
    'Kaisen',
    'Pfiffner',
    'Ritz',
    'Schneider Electric',
    'Siemens',
    'General Electric',
    'Mitsubishi Electric',
    'Toshiba',
    'Westinghouse',
    'Zelisko',
    ],

  DisconnectorDTO: [
    'ABB',
    'ALSTOM',
    'General Electric',
    'MITSHUBISHI',
    'Schneider Electric',
    'Siemens',
    'Toshiba',
    'Westinghouse'
    ],
  PowerCableDTO: [
    'Cadivi',
    'Cadisun',
    'Nexans',
    'LS-Vina',
    'Prysmian Group',
    'Furukawa Electric',
    'Furukawa Co.',
    'Elsewedy Electric',
    'VITHACO',
    'DAPHACO'
  ],
  SurgeArresterDto: [
    'ABB',
    'ALSTOM',
    'Eaton Cooper',
    'General Electric',
    'Hubbell',
    'Mitsubishi Electric',
    'Schneider Electric',
    'Siemens',
    'Toshiba',
    'Westinghouse'
  ]
}

export default MANUFACTURER_MAP